server:
  port: 8081

spring:
    profiles:
       active: dev

    datasource:
        name: root
        url: jdbc:mysql://139.224.9.135:3307/boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: wpg@2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
#spring:
    redis:
        host: 122.112.210.179
        port: 6379
        timeout: 0
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
#    cluster:
#      max-redirects: 5
#      nodes: 127.0.0.1:6380,127.0.0.1:6381
        
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
logging:
   level:
     root: info
   config: classpath:logback.xml
   #file:demo.log
   #path:F:\\demo
   
 
#swagger 配置的两种方式之一  yml 
#swagger:
#  enabled: true
#  title: oms-API
#  description: API文档
#  base-package:  com.op.copyems.Controller
#  base-path: /**
#  exclude-path: /error
#  version: @project.version@
   